### ISSUE TITLE
mintbackup crashes after loading .list

### ISSUE THREAD

**Issue by calexil** [linuxmint/mintbackup#26]
mintbackup
'NoneType' object has no attribute 'summary'
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

**Comment by calexil** [comment]
still happening after update to 2.2.1


'NoneType' object has no attribute 'summary'
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

**Comment by mtwebster** [comment]
I haven't been able to reproduce this.  Can you describe step-by-step how you encounter it?
